### ISSUE TITLE
Aiff support

### ISSUE THREAD

**Issue by drzygote** [Marekkon5/discogstagger#1]
Hi, I use mainly aiffs and some wavs. Aiffs can embed cover art. Is there any way you can add aiff support?
Peace

**Comment by Marekkon5** [comment]
AIFF uses ID3 tags, but they aren't done as usual, and there aren't any Rust libraries for it + ID3 isn't even mentioned in the official spec sheet, so can't do for now, maybe in future.

**Comment by simonsan** [comment]
Why closing the issue though, if you want to do that in the future? Isn't that prone to forget about it?

**Comment by atarbig** [comment]
It would be good to make a traxsource tagger

**Comment by Marekkon5** [comment]
Added
