### ISSUE TITLE
traxtagger

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/discogstagger#3]
It would be good to make traxsource.com tagger. Traxsource have many good tracks, very popular store for djs

**Comment by atarbig** [comment]
Please create traxsource.com tagger

**Comment by bascurtiz** [comment]
@atarbig 
Traxsource Tagger is out now!
Check it out here: https://github.com/Marekkon5/traxsourcetagger
Releases here: https://github.com/Marekkon5/traxsourcetagger/releases
