### ISSUE TITLE
External Drive Support

### ISSUE THREAD

**Issue by thorfinnrowle** [Marekkon5/discogstagger#4]
Hi, i have tried tagging FLAC files located onto an external drive and it says "path is invalid."

When i copy and paste onto my system drive it is able to write over existing tax without an issue.

**Comment by Marekkon5** [comment]
On Windows it seems to be working fine, could you provide the following info please: OS, path shown in UI, partition format (exFAT/NTFS/...) of the drive. Thank you.

**Comment by bascurtiz** [comment]
I have no clue tbh - I tested it on macOS El Capitan , see [demo](https://youtu.be/_E_zaqbb_rw) - works proper.
Using external SSD formatted in exFAT.

**Comment by bascurtiz** [comment]
Tried on macOS Catalina through VM aswell - works proper , see [demo](https://youtu.be/ZFg0I11qBKU).
