### ISSUE TITLE
Flac corruption

### ISSUE THREAD

**Issue by brendan-pike** [Marekkon5/discogstagger#7]
Not sure of the details yet but I found that discogstagger corrupted 11 out of 14 flac files in one album.  I'll try and replicate this soon, I'm now worried its damaged some of my collection.  I was re-tagging [Imany – The Wrong Kind Of War](https://www.discogs.com/master/1052008) at 80 strictness. It was unable to identify 3 songs in the album, so I increased to 85%, then 90% and finally 100%.  Then when trying to play it I found they were corrupt.  Pretty serious issue I'm afraid.

**Comment by Marekkon5** [comment]
We never had such problem, and I just tried it and couldn't reproduce while checking with `ffprobe`. Could you describe more what do you mean by this corruption?

**Comment by brendan-pike** [comment]
Okay, I've just been retesting and no matter what I do this album always ends up corrupted which scares me because I ran it over hundreds of my albums already.  The output looks normal so no clues there, I can only assume its something about the album it doesn't like. If you want I can pass you a copy if you let me know how to do so privately.
I should of mentioned, the output of mediainfo post run looks like this
```
$ mediainfo 01\ Save\ Our\ Soul.flac 
General
Complete name                    : 01 Save Our Soul.flac
File size                                : 25.2 MiB
```
Where pre run it had full tag info.

**Comment by Marekkon5** [comment]
That's weird, never happened to us, just tried and works properly. Does it show the tags in other tag viewers (ie. Kid3)?

You can contact me on Telegram with same username.

**Comment by brendan-pike** [comment]
The file is no longer even playable with VLC etc.  I'll contact you.

**Comment by awsms** [comment]
output of flac -t 01\ Save\ Our\ Soul.flac if you still have the file on your disk by any chance?

**Comment by Marekkon5** [comment]
> output of flac -t 01\ Save\ Our\ Soul.flac if you still have the file on your disk by any chance?

This issue has been resolved (problem was FLAC files with ID3 header). Anyway discogstagger is deprecated, please use onetagger. Thank you
