### ISSUE TITLE
Artist field not been populdated

### ISSUE THREAD

**Issue by brendan-pike** [Marekkon5/discogstagger#9]
I used it on this album https://www.discogs.com/Quincy-Jones-Qs-Jook-Joint/master/60097 and it matched 100% of tracks but it failed to populate the track artists.  I'm wondering if this is a discog issue where featured artists are not credited as track artists?  For example, the track Cool Joe, Mean Joe (Killer Joe) is listed as Quincy Jones Featuring Nancy Wilson, Queen Latifah, Töne Löc.  But only Quincy ends up in the meta data?

**Comment by Marekkon5** [comment]
Hello, we wanted to unite the taggers, to not maintain 3+ projects at once, so we created OneTagger: https://github.com/Marekkon5/onetagger Website: https://onetagger.github.io/

I've fixed the issue, but not yet on master, but will be available in the next release.
